apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: flask-app
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly92YXNpbGprb3ZkYXJrbzpjb2Rld2l0aHZhc2lsamtvdmRhcmtvQGNsdXN0ZXIwLnVwaXU1Lm1vbmdvZGIubmV0L2NsdXN0ZXIw
