name: Flask CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t vasiljkovdarko/taskapp_kiii:latest .

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: |
          docker push vasiljkovdarko/taskapp_kiii:latest

      - name: Deploy & Run Container (Test)
        if: success()
        run: |
          docker run -d -p 5000:5000 vasiljkovdarko/taskapp_kiii:latest
          sleep 10  # Wait for container startup
          curl -v http://localhost:5000 || (echo "Health check failed!" && exit 1)

